version: "3.8"
services:
  app:
    build: .
    ports:
      - "8000:8000"
#    environment:
      # 可在运行时通过环境变量注入 API Key，避免把密钥写入镜像
#      - HEFENG_key=${HEFENG_key}
#      - XINZHI_key=${XINZHI_key}
#      - QWEN_key=${QWEN_key}
    volumes:
      - ./:/app
    command: uvicorn server:app --host 0.0.0.0 --port 8000 --reload
